Practice04
mutcianm/ScalaSpbsu21 pull request #21
Opened 2021-03-17 16:11 UTC by Gor1x

2021-03-17 17:24 UTC, fuCtor requested changes

2021-03-17 17:24 UTC, fuCtor commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  override def map[NT >: T](f: NT => NT): MyGenericList[NT] = f(head) :: tail.map(f)
Не нужно вешать ограничения на результирующий тип. Если мы хотим все числа преобразовать в строки, то тип String никак не связан с Int.

2021-03-17 17:24 UTC, fuCtor commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +        case GenericListBuilder(y, xs) if comparator.compare(x, y) >= 0 => y :: insert(x, xs)
у Ordering есть удобные методы lt gt ltea gteq, можно пользоваться ими.

2021-03-17 21:47 UTC, Gor1x commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +  override def map[NT >: T](f: NT => NT): MyGenericList[NT] = f(head) :: tail.map(f)
Done

2021-03-17 21:48 UTC, Gor1x commented on 04/practice/src/main/scala/org/spbsu/mkn/scala/MyGenericList.scala
> +        case GenericListBuilder(y, xs) if comparator.compare(x, y) >= 0 => y :: insert(x, xs)
Done

2021-03-23 18:43 UTC, fuCtor approved these changes

2021-03-23 20:10 UTC, closed without merging